Import('*')

# -----------------------------------------------------------------------------------
# Get the current working directory
# 
sconscript_cwd = Dir('.').srcnode().abspath


# -----------------------------------------------------------------------------------
# Specific macro definitions
# 

# -----------------------------------------------------------------------------------
# Driver files
# 
includes += [sconscript_cwd]
sources  += Glob('*.cpp')

